include:
  - states.core.pkgs.build-essential
  - states.core.pkgs.curl
  - states.core.pkgs.git
  - states.core.pkgs.htop
  - states.core.pkgs.mytop
  - states.core.pkgs.nmon
  - states.core.pkgs.perl
  - states.core.pkgs.perllibs
  - states.core.pkgs.screen
  - states.core.pkgs.tmux
  - states.core.pkgs.vim
  - states.core.pkgs.svn
  - states.core.pkgs.gplusplus
  - states.core.pkgs.make
